package day4task;

public class ExceptionExample {

    public static void main(String[] args) {
        
        try {
            int[] numbers = {1, 2, 3, 4, 5}; 

            for (int i = 0; i < numbers.length; i++) {
                numbers[i] = i + 1;
            }

            System.out.println(numbers[1]);

            numbers[5] = 6;
            
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Caught ArrayIndexOutOfBoundsException: " + e.getMessage());
          
        } finally {
            System.out.println("Finished array access block.\n");
        }

        try {
            String text = "Anitha";
            String text1 = null;
            System.out.println(text.length()); 
            System.out.println(text1.length()); 

        } catch (NullPointerException e) {
            System.out.println("Caught NullPointerException: " + e.getMessage());
        } finally {
            System.out.println("Finished string access block.");
        }
    }
}
